name: Update AI Leader Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1' # Runs at 8:00 UTC every Monday

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # New Step: Install the libraries we need for searching and scraping
      - name: Install dependencies
        run: pip install requests beautifulsoup4 google-search-results

      - name: Run the scraper script
        # New: Give the script access to our secret API key
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python scraper.py

      - name: Commit and push if data changed
        run: |
          git config --global user.name "AI-Leader-Bot"
          git config --global user.email "bot@github.com"
          git add leaders.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Discovered and updated AI leaders"
            git push
          fi
